"""add llm_config_pending to instances

Revision ID: 0873f1390f28
Revises: c1437ab4f194
Create Date: 2026-04-07 23:28:01.581344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0873f1390f28'
down_revision: Union[str, Sequence[str], None] = 'c1437ab4f194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('llm_config_pending', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'llm_config_pending')
    # ### end Alembic commands ###
