"""add_external_agent_chat_sessions_and_messages

Revision ID: 0e84015e8bd6
Revises: 8eab2c5e6eef
Create Date: 2026-06-25 11:28:49.523613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e84015e8bd6'
down_revision: Union[str, Sequence[str], None] = '8eab2c5e6eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_agent_chat_sessions',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['external_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_agent_chat_sessions_agent_id'), 'external_agent_chat_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_external_agent_chat_sessions_deleted_at'), 'external_agent_chat_sessions', ['deleted_at'], unique=False)
    op.create_table('external_agent_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['external_agent_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_agent_messages_deleted_at'), 'external_agent_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_external_agent_messages_session_id'), 'external_agent_messages', ['session_id'], unique=False)
    op.drop_index(op.f('ix_performance_snapshots_deleted_at'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_instance_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_workspace_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_topology_audit_logs_workspace_id'), table_name='topology_audit_logs')
    op.drop_table('topology_audit_logs')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_column('clusters', 'token_expires_at')
    op.drop_column('clusters', 'kubeconfig_encrypted')
    op.drop_column('clusters', 'api_server_url')
    op.drop_column('clusters', 'auth_type')
    op.drop_column('clusters', 'k8s_version')
    op.drop_column('clusters', 'provider')
    op.drop_column('clusters', 'ingress_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('ingress_class', sa.VARCHAR(length=32), server_default=sa.text("'nginx'::character varying"), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('provider', sa.VARCHAR(length=16), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('k8s_version', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('clusters', sa.Column('auth_type', sa.VARCHAR(length=32), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('api_server_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('clusters', sa.Column('kubeconfig_encrypted', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table('plans',
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('max_instances', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_cpu_per_instance', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('max_mem_per_instance', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('allowed_specs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dedicated_cluster', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('price_monthly', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey')),
    sa.UniqueConstraint('name', name=op.f('plans_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.create_table('topology_audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actor_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('topology_audit_logs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('topology_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_topology_audit_logs_workspace_id'), 'topology_audit_logs', ['workspace_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('performance_snapshots_pkey'))
    )
    op.create_index(op.f('ix_performance_snapshots_workspace_id'), 'performance_snapshots', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_instance_id'), 'performance_snapshots', ['instance_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_deleted_at'), 'performance_snapshots', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_external_agent_messages_session_id'), table_name='external_agent_messages')
    op.drop_index(op.f('ix_external_agent_messages_deleted_at'), table_name='external_agent_messages')
    op.drop_table('external_agent_messages')
    op.drop_index(op.f('ix_external_agent_chat_sessions_deleted_at'), table_name='external_agent_chat_sessions')
    op.drop_index(op.f('ix_external_agent_chat_sessions_agent_id'), table_name='external_agent_chat_sessions')
    op.drop_table('external_agent_chat_sessions')
    # ### end Alembic commands ###
