"""workspace_task_add_prompt_completion_token_cost

Revision ID: 6ec551602b22
Revises: 1cabdd078ae2
Create Date: 2026-04-05 06:13:56.387278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec551602b22'
down_revision: Union[str, Sequence[str], None] = '1cabdd078ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_tasks', sa.Column('prompt_token_cost', sa.Integer(), nullable=True))
    op.add_column('workspace_tasks', sa.Column('completion_token_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_tasks', 'completion_token_cost')
    op.drop_column('workspace_tasks', 'prompt_token_cost')
    # ### end Alembic commands ###
