"""baseline

Revision ID: 8d465624ee1f
Revises: 
Create Date: 2026-03-10 21:30:50.135587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d465624ee1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_states',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('half_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_states_deleted_at'), 'circuit_states', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_circuit_states_node_id'), 'circuit_states', ['node_id'], unique=False)
    op.create_index(op.f('ix_circuit_states_workspace_id'), 'circuit_states', ['workspace_id'], unique=False)
    op.create_index('uq_circuit_state_node_workspace', 'circuit_states', ['node_id', 'workspace_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('clusters',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('kubeconfig_encrypted', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_server_url', sa.String(length=512), nullable=True),
    sa.Column('k8s_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('ingress_class', sa.String(length=32), nullable=False),
    sa.Column('proxy_endpoint', sa.String(length=512), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_clusters_deleted_at'), 'clusters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_clusters_org_id'), 'clusters', ['org_id'], unique=False)
    op.create_table('dead_letters',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('original_priority', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=2048), nullable=True),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recoverable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_deleted_at'), 'dead_letters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dead_letters_message_id'), 'dead_letters', ['message_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_target_node_id'), 'dead_letters', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_workspace_id'), 'dead_letters', ['workspace_id'], unique=False)
    op.create_table('delivery_logs',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transport', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_logs_deleted_at'), 'delivery_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_delivery_logs_message_id'), 'delivery_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_delivery_logs_target_node_id'), 'delivery_logs', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_delivery_logs_workspace_id'), 'delivery_logs', ['workspace_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('source_node_id', sa.String(length=36), nullable=True),
    sa.Column('target_node_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('backend_instance_id', sa.String(length=36), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_deleted_at'), 'event_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_message_id'), 'event_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_event_logs_trace_id'), 'event_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_event_logs_workspace_id'), 'event_logs', ['workspace_id'], unique=False)
    op.create_table('idempotency_cache',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_cache_deleted_at'), 'idempotency_cache', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_idempotency_cache_message_id'), 'idempotency_cache', ['message_id'], unique=True)
    op.create_table('message_queue',
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_queue_deleted_at'), 'message_queue', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_message_queue_status'), 'message_queue', ['status'], unique=False)
    op.create_index(op.f('ix_message_queue_target_node_id'), 'message_queue', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_message_queue_workspace_id'), 'message_queue', ['workspace_id'], unique=False)
    op.create_table('message_schemas',
    sa.Column('type_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_def', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_schemas_deleted_at'), 'message_schemas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_message_schemas_type_id'), 'message_schemas', ['type_id'], unique=False)
    op.create_index('uq_message_schema_type_version', 'message_schemas', ['type_id', 'version'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('node_type_definitions',
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('routing_role', sa.String(length=32), nullable=False),
    sa.Column('transport', sa.String(length=64), nullable=True),
    sa.Column('card_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('propagates', sa.Boolean(), nullable=False),
    sa.Column('consumes', sa.Boolean(), nullable=False),
    sa.Column('is_addressable', sa.Boolean(), nullable=False),
    sa.Column('can_originate', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_type_definitions_deleted_at'), 'node_type_definitions', ['deleted_at'], unique=False)
    op.create_index('uq_node_type_definitions_type_id', 'node_type_definitions', ['type_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('organizations',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.Column('max_cpu_total', sa.String(length=16), nullable=False),
    sa.Column('max_mem_total', sa.String(length=16), nullable=False),
    sa.Column('max_storage_total', sa.String(length=16), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('performance_snapshots',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_deleted_at'), 'performance_snapshots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_instance_id'), 'performance_snapshots', ['instance_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_workspace_id'), 'performance_snapshots', ['workspace_id'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.Column('max_cpu_per_instance', sa.String(length=16), nullable=False),
    sa.Column('max_mem_per_instance', sa.String(length=16), nullable=False),
    sa.Column('allowed_specs', sa.Text(), nullable=False),
    sa.Column('dedicated_cluster', sa.Boolean(), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.create_table('sse_connections',
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('backend_instance_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sse_connections_backend_instance_id'), 'sse_connections', ['backend_instance_id'], unique=False)
    op.create_index(op.f('ix_sse_connections_connection_id'), 'sse_connections', ['connection_id'], unique=True)
    op.create_index(op.f('ix_sse_connections_deleted_at'), 'sse_connections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sse_connections_instance_id'), 'sse_connections', ['instance_id'], unique=False)
    op.create_index(op.f('ix_sse_connections_workspace_id'), 'sse_connections', ['workspace_id'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_deleted_at'), 'system_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_org_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_table('admin_memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_memberships_deleted_at'), 'admin_memberships', ['deleted_at'], unique=False)
    op.create_index('uq_admin_membership', 'admin_memberships', ['user_id', 'org_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('genomes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('gene_slugs', sa.Text(), nullable=True),
    sa.Column('config_override', sa.Text(), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genomes_deleted_at'), 'genomes', ['deleted_at'], unique=False)
    op.create_index('uq_genomes_slug_org_active', 'genomes', ['slug', 'org_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('org_llm_keys',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('org_token_limit', sa.BigInteger(), nullable=True),
    sa.Column('system_token_limit', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_llm_keys_deleted_at'), 'org_llm_keys', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_org_llm_keys_org_id'), 'org_llm_keys', ['org_id'], unique=False)
    op.create_table('org_memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('job_title', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_memberships_deleted_at'), 'org_memberships', ['deleted_at'], unique=False)
    op.create_index('uq_org_membership', 'org_memberships', ['user_id', 'org_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('org_oauth_bindings',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_tenant_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_oauth_bindings_deleted_at'), 'org_oauth_bindings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_org_oauth_bindings_provider'), 'org_oauth_bindings', ['provider'], unique=False)
    op.create_index('uq_oauth_provider_tenant', 'org_oauth_bindings', ['provider', 'provider_tenant_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('org_smtp_configs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=128), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_index(op.f('ix_org_smtp_configs_deleted_at'), 'org_smtp_configs', ['deleted_at'], unique=False)
    op.create_table('user_llm_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_type', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_llm_keys_deleted_at'), 'user_llm_keys', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_llm_keys_user_id'), 'user_llm_keys', ['user_id'], unique=False)
    op.create_index('uq_user_llm_keys_user_provider', 'user_llm_keys', ['user_id', 'provider'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('user_oauth_connections',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('provider_tenant_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_connections_deleted_at'), 'user_oauth_connections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_oauth_connections_provider'), 'user_oauth_connections', ['provider'], unique=False)
    op.create_index('uq_oauth_provider_user', 'user_oauth_connections', ['provider', 'provider_user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('workspace_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('topology_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('blackboard_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('gene_assignments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_templates_deleted_at'), 'workspace_templates', ['deleted_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('decoration_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_deleted_at'), 'workspaces', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspaces_org_id'), 'workspaces', ['org_id'], unique=False)
    op.create_table('blackboards',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('auto_summary', sa.Text(), nullable=False),
    sa.Column('manual_notes', sa.Text(), nullable=False),
    sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_index(op.f('ix_blackboards_deleted_at'), 'blackboards', ['deleted_at'], unique=False)
    op.create_table('corridor_hexes',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('hex_q', sa.Integer(), nullable=False),
    sa.Column('hex_r', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridor_hexes_deleted_at'), 'corridor_hexes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_corridor_hexes_workspace_id'), 'corridor_hexes', ['workspace_id'], unique=False)
    op.create_index('uq_corridor_hex_pos', 'corridor_hexes', ['workspace_id', 'hex_q', 'hex_r'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('decision_records',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('agent_instance_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('proposal', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('review_type', sa.String(length=10), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_agent_instance_id'), 'decision_records', ['agent_instance_id'], unique=False)
    op.create_index(op.f('ix_decision_records_deleted_at'), 'decision_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_decision_records_workspace_id'), 'decision_records', ['workspace_id'], unique=False)
    op.create_table('genome_ratings',
    sa.Column('genome_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['genomes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genome_ratings_deleted_at'), 'genome_ratings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_genome_ratings_genome_id'), 'genome_ratings', ['genome_id'], unique=False)
    op.create_index('uq_genome_rating_user', 'genome_ratings', ['genome_id', 'user_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('hex_connections',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('hex_a_q', sa.Integer(), nullable=False),
    sa.Column('hex_a_r', sa.Integer(), nullable=False),
    sa.Column('hex_b_q', sa.Integer(), nullable=False),
    sa.Column('hex_b_r', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('auto_created', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hex_connections_deleted_at'), 'hex_connections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hex_connections_workspace_id'), 'hex_connections', ['workspace_id'], unique=False)
    op.create_index('uq_hex_connection_pair', 'hex_connections', ['workspace_id', 'hex_a_q', 'hex_a_r', 'hex_b_q', 'hex_b_r'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('human_hexes',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hex_q', sa.Integer(), nullable=False),
    sa.Column('hex_r', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('display_color', sa.String(length=20), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('channel_config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_hexes_deleted_at'), 'human_hexes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_human_hexes_user_id'), 'human_hexes', ['user_id'], unique=False)
    op.create_index(op.f('ix_human_hexes_workspace_id'), 'human_hexes', ['workspace_id'], unique=False)
    op.create_index('uq_human_hex_pos', 'human_hexes', ['workspace_id', 'hex_q', 'hex_r'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('instances',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('image_version', sa.String(length=64), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('cpu_request', sa.String(length=16), nullable=False),
    sa.Column('cpu_limit', sa.String(length=16), nullable=False),
    sa.Column('mem_request', sa.String(length=16), nullable=False),
    sa.Column('mem_limit', sa.String(length=16), nullable=False),
    sa.Column('service_type', sa.String(length=16), nullable=False),
    sa.Column('ingress_domain', sa.String(length=256), nullable=True),
    sa.Column('proxy_token', sa.String(length=64), nullable=True),
    sa.Column('wp_api_key', sa.String(length=96), nullable=True),
    sa.Column('env_vars', sa.Text(), nullable=True),
    sa.Column('quota_cpu', sa.String(length=16), nullable=False),
    sa.Column('quota_mem', sa.String(length=16), nullable=False),
    sa.Column('quota_max_pods', sa.Integer(), nullable=False),
    sa.Column('storage_class', sa.String(length=64), nullable=False),
    sa.Column('storage_size', sa.String(length=16), nullable=False),
    sa.Column('advanced_config', sa.Text(), nullable=True),
    sa.Column('llm_providers', sa.JSON(), nullable=True),
    sa.Column('pending_config', sa.Text(), nullable=True),
    sa.Column('available_replicas', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('compute_provider', sa.String(length=32), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('hex_position_q', sa.Integer(), nullable=False),
    sa.Column('hex_position_r', sa.Integer(), nullable=False),
    sa.Column('agent_display_name', sa.String(length=64), nullable=True),
    sa.Column('agent_label', sa.String(length=128), nullable=True),
    sa.Column('agent_theme_color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances_deleted_at'), 'instances', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_instances_org_id'), 'instances', ['org_id'], unique=False)
    op.create_index(op.f('ix_instances_proxy_token'), 'instances', ['proxy_token'], unique=True)
    op.create_index(op.f('ix_instances_workspace_id'), 'instances', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_instances_wp_api_key'), 'instances', ['wp_api_key'], unique=True)
    op.create_index('uq_instances_slug_org_active', 'instances', ['slug', 'org_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('node_cards',
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('hex_q', sa.Integer(), nullable=False),
    sa.Column('hex_r', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_cards_deleted_at'), 'node_cards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_node_cards_node_id'), 'node_cards', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_cards_node_type'), 'node_cards', ['node_type'], unique=False)
    op.create_index(op.f('ix_node_cards_workspace_id'), 'node_cards', ['workspace_id'], unique=False)
    op.create_index('uq_node_card_hex_pos', 'node_cards', ['workspace_id', 'hex_q', 'hex_r'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_node_card_node_workspace', 'node_cards', ['node_id', 'workspace_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('topology_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_audit_logs_workspace_id'), 'topology_audit_logs', ['workspace_id'], unique=False)
    op.create_table('trust_policies',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('agent_instance_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('grant_type', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_policies_agent_instance_id'), 'trust_policies', ['agent_instance_id'], unique=False)
    op.create_index(op.f('ix_trust_policies_deleted_at'), 'trust_policies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_trust_policies_workspace_id'), 'trust_policies', ['workspace_id'], unique=False)
    op.create_table('user_llm_configs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('key_source', sa.String(length=16), nullable=False),
    sa.Column('org_llm_key_id', sa.String(length=36), nullable=True),
    sa.Column('selected_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['org_llm_key_id'], ['org_llm_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_llm_configs_deleted_at'), 'user_llm_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_llm_configs_org_id'), 'user_llm_configs', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_llm_configs_user_id'), 'user_llm_configs', ['user_id'], unique=False)
    op.create_index('uq_user_llm_configs_user_org_provider', 'user_llm_configs', ['user_id', 'org_id', 'provider'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('workspace_files',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('tos_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_files_deleted_at'), 'workspace_files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_files_workspace_id'), 'workspace_files', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('hex_q', sa.Integer(), nullable=True),
    sa.Column('hex_r', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('channel_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('display_color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_deleted_at'), 'workspace_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index('uq_workspace_member', 'workspace_members', ['workspace_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('workspace_messages',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('sender_name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('target_instance_id', sa.String(length=36), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_messages_deleted_at'), 'workspace_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_messages_workspace_id'), 'workspace_messages', ['workspace_id'], unique=False)
    op.create_table('workspace_objectives',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('obj_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['workspace_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_objectives_deleted_at'), 'workspace_objectives', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_objectives_obj_type'), 'workspace_objectives', ['obj_type'], unique=False)
    op.create_index(op.f('ix_workspace_objectives_parent_id'), 'workspace_objectives', ['parent_id'], unique=False)
    op.create_index(op.f('ix_workspace_objectives_workspace_id'), 'workspace_objectives', ['workspace_id'], unique=False)
    op.create_table('workspace_schedules',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cron_expr', sa.String(length=50), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_schedules_deleted_at'), 'workspace_schedules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_schedules_workspace_id'), 'workspace_schedules', ['workspace_id'], unique=False)
    op.create_table('deploy_records',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('image_version', sa.String(length=64), nullable=True),
    sa.Column('replicas', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploy_records_deleted_at'), 'deploy_records', ['deleted_at'], unique=False)
    op.create_table('evolution_events',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('gene_id', sa.String(length=36), nullable=True),
    sa.Column('genome_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('gene_name', sa.String(length=128), nullable=False),
    sa.Column('gene_slug', sa.String(length=128), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolution_events_deleted_at'), 'evolution_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evolution_events_event_type'), 'evolution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_evolution_events_gene_id'), 'evolution_events', ['gene_id'], unique=False)
    op.create_index(op.f('ix_evolution_events_instance_id'), 'evolution_events', ['instance_id'], unique=False)
    op.create_table('genes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('manifest', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('synergies', sa.Text(), nullable=True),
    sa.Column('parent_gene_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_instance_id', sa.String(length=36), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('effectiveness_score', sa.Float(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genes_deleted_at'), 'genes', ['deleted_at'], unique=False)
    op.create_index('uq_genes_slug_org_active', 'genes', ['slug', 'org_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('instance_mcp_servers',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('args', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('env', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_gene_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_mcp_servers_deleted_at'), 'instance_mcp_servers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_instance_mcp_servers_instance_id'), 'instance_mcp_servers', ['instance_id'], unique=False)
    op.create_table('instance_members',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instance_member_instance', 'instance_members', ['instance_id'], unique=False)
    op.create_index('ix_instance_member_user', 'instance_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_instance_members_deleted_at'), 'instance_members', ['deleted_at'], unique=False)
    op.create_index('uq_instance_member_active', 'instance_members', ['instance_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('instance_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('gene_slugs', sa.Text(), nullable=True),
    sa.Column('source_instance_id', sa.String(length=36), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_templates_deleted_at'), 'instance_templates', ['deleted_at'], unique=False)
    op.create_index('uq_instance_templates_slug_org_active', 'instance_templates', ['slug', 'org_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_llm_key_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['org_llm_key_id'], ['org_llm_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_logs_created_at'), 'llm_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_logs_org_llm_key_id'), 'llm_usage_logs', ['org_llm_key_id'], unique=False)
    op.create_table('workspace_agents',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('hex_q', sa.Integer(), nullable=False),
    sa.Column('hex_r', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_agents_deleted_at'), 'workspace_agents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_agents_instance_id'), 'workspace_agents', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workspace_agents_workspace_id'), 'workspace_agents', ['workspace_id'], unique=False)
    op.create_index('uq_workspace_agent', 'workspace_agents', ['workspace_id', 'instance_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('workspace_tasks',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assignee_instance_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_instance_id', sa.String(length=36), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('token_cost', sa.Integer(), nullable=True),
    sa.Column('blocker_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_instance_id'], ['instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_instance_id'], ['instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_tasks_assignee_instance_id'), 'workspace_tasks', ['assignee_instance_id'], unique=False)
    op.create_index(op.f('ix_workspace_tasks_deleted_at'), 'workspace_tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_tasks_status'), 'workspace_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_workspace_tasks_workspace_id'), 'workspace_tasks', ['workspace_id'], unique=False)
    op.create_table('gene_effect_logs',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('gene_id', sa.String(length=36), nullable=False),
    sa.Column('metric_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_effect_logs_deleted_at'), 'gene_effect_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_gene_effect_logs_gene_id'), 'gene_effect_logs', ['gene_id'], unique=False)
    op.create_index(op.f('ix_gene_effect_logs_instance_id'), 'gene_effect_logs', ['instance_id'], unique=False)
    op.create_table('gene_ratings',
    sa.Column('gene_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_ratings_deleted_at'), 'gene_ratings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_gene_ratings_gene_id'), 'gene_ratings', ['gene_id'], unique=False)
    op.create_index('uq_gene_rating_user', 'gene_ratings', ['gene_id', 'user_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('instance_genes',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('gene_id', sa.String(length=36), nullable=False),
    sa.Column('genome_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('installed_version', sa.String(length=16), nullable=True),
    sa.Column('learning_output', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.Text(), nullable=True),
    sa.Column('agent_self_eval', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('variant_published', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['genome_id'], ['genomes.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_genes_deleted_at'), 'instance_genes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_instance_genes_gene_id'), 'instance_genes', ['gene_id'], unique=False)
    op.create_index(op.f('ix_instance_genes_instance_id'), 'instance_genes', ['instance_id'], unique=False)
    op.create_index('uq_instance_gene_active', 'instance_genes', ['instance_id', 'gene_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('org_required_genes',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('gene_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_required_genes_deleted_at'), 'org_required_genes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_org_required_genes_org_id'), 'org_required_genes', ['org_id'], unique=False)
    op.create_index('uq_org_required_gene_active', 'org_required_genes', ['org_id', 'gene_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key('fk_clusters_created_by', 'clusters', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_clusters_org_id', 'clusters', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key('fk_organizations_cluster_id', 'organizations', 'clusters', ['cluster_id'], ['id'])
    op.create_foreign_key('fk_users_current_org_id', 'users', 'organizations', ['current_org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_current_org_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_organizations_cluster_id', 'organizations', type_='foreignkey')
    op.drop_constraint('fk_clusters_org_id', 'clusters', type_='foreignkey')
    op.drop_constraint('fk_clusters_created_by', 'clusters', type_='foreignkey')
    op.drop_index('uq_org_required_gene_active', table_name='org_required_genes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_org_required_genes_org_id'), table_name='org_required_genes')
    op.drop_index(op.f('ix_org_required_genes_deleted_at'), table_name='org_required_genes')
    op.drop_table('org_required_genes')
    op.drop_index('uq_instance_gene_active', table_name='instance_genes', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_instance_genes_instance_id'), table_name='instance_genes')
    op.drop_index(op.f('ix_instance_genes_gene_id'), table_name='instance_genes')
    op.drop_index(op.f('ix_instance_genes_deleted_at'), table_name='instance_genes')
    op.drop_table('instance_genes')
    op.drop_index('uq_gene_rating_user', table_name='gene_ratings', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_gene_ratings_gene_id'), table_name='gene_ratings')
    op.drop_index(op.f('ix_gene_ratings_deleted_at'), table_name='gene_ratings')
    op.drop_table('gene_ratings')
    op.drop_index(op.f('ix_gene_effect_logs_instance_id'), table_name='gene_effect_logs')
    op.drop_index(op.f('ix_gene_effect_logs_gene_id'), table_name='gene_effect_logs')
    op.drop_index(op.f('ix_gene_effect_logs_deleted_at'), table_name='gene_effect_logs')
    op.drop_table('gene_effect_logs')
    op.drop_index(op.f('ix_workspace_tasks_workspace_id'), table_name='workspace_tasks')
    op.drop_index(op.f('ix_workspace_tasks_status'), table_name='workspace_tasks')
    op.drop_index(op.f('ix_workspace_tasks_deleted_at'), table_name='workspace_tasks')
    op.drop_index(op.f('ix_workspace_tasks_assignee_instance_id'), table_name='workspace_tasks')
    op.drop_table('workspace_tasks')
    op.drop_index('uq_workspace_agent', table_name='workspace_agents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_workspace_agents_workspace_id'), table_name='workspace_agents')
    op.drop_index(op.f('ix_workspace_agents_instance_id'), table_name='workspace_agents')
    op.drop_index(op.f('ix_workspace_agents_deleted_at'), table_name='workspace_agents')
    op.drop_table('workspace_agents')
    op.drop_index(op.f('ix_llm_usage_logs_org_llm_key_id'), table_name='llm_usage_logs')
    op.drop_index(op.f('ix_llm_usage_logs_created_at'), table_name='llm_usage_logs')
    op.drop_table('llm_usage_logs')
    op.drop_index('uq_instance_templates_slug_org_active', table_name='instance_templates', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_instance_templates_deleted_at'), table_name='instance_templates')
    op.drop_table('instance_templates')
    op.drop_index('uq_instance_member_active', table_name='instance_members', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_instance_members_deleted_at'), table_name='instance_members')
    op.drop_index('ix_instance_member_user', table_name='instance_members')
    op.drop_index('ix_instance_member_instance', table_name='instance_members')
    op.drop_table('instance_members')
    op.drop_index(op.f('ix_instance_mcp_servers_instance_id'), table_name='instance_mcp_servers')
    op.drop_index(op.f('ix_instance_mcp_servers_deleted_at'), table_name='instance_mcp_servers')
    op.drop_table('instance_mcp_servers')
    op.drop_index('uq_genes_slug_org_active', table_name='genes', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_genes_deleted_at'), table_name='genes')
    op.drop_table('genes')
    op.drop_index(op.f('ix_evolution_events_instance_id'), table_name='evolution_events')
    op.drop_index(op.f('ix_evolution_events_gene_id'), table_name='evolution_events')
    op.drop_index(op.f('ix_evolution_events_event_type'), table_name='evolution_events')
    op.drop_index(op.f('ix_evolution_events_deleted_at'), table_name='evolution_events')
    op.drop_table('evolution_events')
    op.drop_index(op.f('ix_deploy_records_deleted_at'), table_name='deploy_records')
    op.drop_table('deploy_records')
    op.drop_index(op.f('ix_workspace_schedules_workspace_id'), table_name='workspace_schedules')
    op.drop_index(op.f('ix_workspace_schedules_deleted_at'), table_name='workspace_schedules')
    op.drop_table('workspace_schedules')
    op.drop_index(op.f('ix_workspace_objectives_workspace_id'), table_name='workspace_objectives')
    op.drop_index(op.f('ix_workspace_objectives_parent_id'), table_name='workspace_objectives')
    op.drop_index(op.f('ix_workspace_objectives_obj_type'), table_name='workspace_objectives')
    op.drop_index(op.f('ix_workspace_objectives_deleted_at'), table_name='workspace_objectives')
    op.drop_table('workspace_objectives')
    op.drop_index(op.f('ix_workspace_messages_workspace_id'), table_name='workspace_messages')
    op.drop_index(op.f('ix_workspace_messages_deleted_at'), table_name='workspace_messages')
    op.drop_table('workspace_messages')
    op.drop_index('uq_workspace_member', table_name='workspace_members', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_deleted_at'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspace_files_workspace_id'), table_name='workspace_files')
    op.drop_index(op.f('ix_workspace_files_deleted_at'), table_name='workspace_files')
    op.drop_table('workspace_files')
    op.drop_index('uq_user_llm_configs_user_org_provider', table_name='user_llm_configs', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_user_llm_configs_user_id'), table_name='user_llm_configs')
    op.drop_index(op.f('ix_user_llm_configs_org_id'), table_name='user_llm_configs')
    op.drop_index(op.f('ix_user_llm_configs_deleted_at'), table_name='user_llm_configs')
    op.drop_table('user_llm_configs')
    op.drop_index(op.f('ix_trust_policies_workspace_id'), table_name='trust_policies')
    op.drop_index(op.f('ix_trust_policies_deleted_at'), table_name='trust_policies')
    op.drop_index(op.f('ix_trust_policies_agent_instance_id'), table_name='trust_policies')
    op.drop_table('trust_policies')
    op.drop_index(op.f('ix_topology_audit_logs_workspace_id'), table_name='topology_audit_logs')
    op.drop_table('topology_audit_logs')
    op.drop_index('uq_node_card_node_workspace', table_name='node_cards', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_node_card_hex_pos', table_name='node_cards', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_node_cards_workspace_id'), table_name='node_cards')
    op.drop_index(op.f('ix_node_cards_node_type'), table_name='node_cards')
    op.drop_index(op.f('ix_node_cards_node_id'), table_name='node_cards')
    op.drop_index(op.f('ix_node_cards_deleted_at'), table_name='node_cards')
    op.drop_table('node_cards')
    op.drop_index('uq_instances_slug_org_active', table_name='instances', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_instances_wp_api_key'), table_name='instances')
    op.drop_index(op.f('ix_instances_workspace_id'), table_name='instances')
    op.drop_index(op.f('ix_instances_proxy_token'), table_name='instances')
    op.drop_index(op.f('ix_instances_org_id'), table_name='instances')
    op.drop_index(op.f('ix_instances_deleted_at'), table_name='instances')
    op.drop_table('instances')
    op.drop_index('uq_human_hex_pos', table_name='human_hexes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_human_hexes_workspace_id'), table_name='human_hexes')
    op.drop_index(op.f('ix_human_hexes_user_id'), table_name='human_hexes')
    op.drop_index(op.f('ix_human_hexes_deleted_at'), table_name='human_hexes')
    op.drop_table('human_hexes')
    op.drop_index('uq_hex_connection_pair', table_name='hex_connections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_hex_connections_workspace_id'), table_name='hex_connections')
    op.drop_index(op.f('ix_hex_connections_deleted_at'), table_name='hex_connections')
    op.drop_table('hex_connections')
    op.drop_index('uq_genome_rating_user', table_name='genome_ratings', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_genome_ratings_genome_id'), table_name='genome_ratings')
    op.drop_index(op.f('ix_genome_ratings_deleted_at'), table_name='genome_ratings')
    op.drop_table('genome_ratings')
    op.drop_index(op.f('ix_decision_records_workspace_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_deleted_at'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_agent_instance_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index('uq_corridor_hex_pos', table_name='corridor_hexes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_corridor_hexes_workspace_id'), table_name='corridor_hexes')
    op.drop_index(op.f('ix_corridor_hexes_deleted_at'), table_name='corridor_hexes')
    op.drop_table('corridor_hexes')
    op.drop_index(op.f('ix_blackboards_deleted_at'), table_name='blackboards')
    op.drop_table('blackboards')
    op.drop_index(op.f('ix_workspaces_org_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_deleted_at'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workspace_templates_deleted_at'), table_name='workspace_templates')
    op.drop_table('workspace_templates')
    op.drop_index('uq_oauth_provider_user', table_name='user_oauth_connections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_user_oauth_connections_provider'), table_name='user_oauth_connections')
    op.drop_index(op.f('ix_user_oauth_connections_deleted_at'), table_name='user_oauth_connections')
    op.drop_table('user_oauth_connections')
    op.drop_index('uq_user_llm_keys_user_provider', table_name='user_llm_keys', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_user_llm_keys_user_id'), table_name='user_llm_keys')
    op.drop_index(op.f('ix_user_llm_keys_deleted_at'), table_name='user_llm_keys')
    op.drop_table('user_llm_keys')
    op.drop_index(op.f('ix_org_smtp_configs_deleted_at'), table_name='org_smtp_configs')
    op.drop_table('org_smtp_configs')
    op.drop_index('uq_oauth_provider_tenant', table_name='org_oauth_bindings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_org_oauth_bindings_provider'), table_name='org_oauth_bindings')
    op.drop_index(op.f('ix_org_oauth_bindings_deleted_at'), table_name='org_oauth_bindings')
    op.drop_table('org_oauth_bindings')
    op.drop_index('uq_org_membership', table_name='org_memberships', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_org_memberships_deleted_at'), table_name='org_memberships')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_org_llm_keys_org_id'), table_name='org_llm_keys')
    op.drop_index(op.f('ix_org_llm_keys_deleted_at'), table_name='org_llm_keys')
    op.drop_table('org_llm_keys')
    op.drop_index('uq_genomes_slug_org_active', table_name='genomes', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_genomes_deleted_at'), table_name='genomes')
    op.drop_table('genomes')
    op.drop_index('uq_admin_membership', table_name='admin_memberships', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_admin_memberships_deleted_at'), table_name='admin_memberships')
    op.drop_table('admin_memberships')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_deleted_at'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sse_connections_workspace_id'), table_name='sse_connections')
    op.drop_index(op.f('ix_sse_connections_instance_id'), table_name='sse_connections')
    op.drop_index(op.f('ix_sse_connections_deleted_at'), table_name='sse_connections')
    op.drop_index(op.f('ix_sse_connections_connection_id'), table_name='sse_connections')
    op.drop_index(op.f('ix_sse_connections_backend_instance_id'), table_name='sse_connections')
    op.drop_table('sse_connections')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_performance_snapshots_workspace_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_instance_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_deleted_at'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('uq_node_type_definitions_type_id', table_name='node_type_definitions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_node_type_definitions_deleted_at'), table_name='node_type_definitions')
    op.drop_table('node_type_definitions')
    op.drop_index('uq_message_schema_type_version', table_name='message_schemas', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_message_schemas_type_id'), table_name='message_schemas')
    op.drop_index(op.f('ix_message_schemas_deleted_at'), table_name='message_schemas')
    op.drop_table('message_schemas')
    op.drop_index(op.f('ix_message_queue_workspace_id'), table_name='message_queue')
    op.drop_index(op.f('ix_message_queue_target_node_id'), table_name='message_queue')
    op.drop_index(op.f('ix_message_queue_status'), table_name='message_queue')
    op.drop_index(op.f('ix_message_queue_deleted_at'), table_name='message_queue')
    op.drop_table('message_queue')
    op.drop_index(op.f('ix_idempotency_cache_message_id'), table_name='idempotency_cache')
    op.drop_index(op.f('ix_idempotency_cache_deleted_at'), table_name='idempotency_cache')
    op.drop_table('idempotency_cache')
    op.drop_index(op.f('ix_event_logs_workspace_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_trace_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_message_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_deleted_at'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_delivery_logs_workspace_id'), table_name='delivery_logs')
    op.drop_index(op.f('ix_delivery_logs_target_node_id'), table_name='delivery_logs')
    op.drop_index(op.f('ix_delivery_logs_message_id'), table_name='delivery_logs')
    op.drop_index(op.f('ix_delivery_logs_deleted_at'), table_name='delivery_logs')
    op.drop_table('delivery_logs')
    op.drop_index(op.f('ix_dead_letters_workspace_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_target_node_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_message_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_deleted_at'), table_name='dead_letters')
    op.drop_table('dead_letters')
    op.drop_index(op.f('ix_clusters_org_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_deleted_at'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index('uq_circuit_state_node_workspace', table_name='circuit_states', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_circuit_states_workspace_id'), table_name='circuit_states')
    op.drop_index(op.f('ix_circuit_states_node_id'), table_name='circuit_states')
    op.drop_index(op.f('ix_circuit_states_deleted_at'), table_name='circuit_states')
    op.drop_table('circuit_states')
    # ### end Alembic commands ###
