"""add_last_fired_at_to_automation_tasks

Revision ID: 8e5ee799a109
Revises: 91e87ce21726
Create Date: 2026-06-12 08:36:20.227817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5ee799a109'
down_revision: Union[str, Sequence[str], None] = '91e87ce21726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_tasks', sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_tasks', 'last_fired_at')
    # ### end Alembic commands ###
