"""add allowed_models to org_llm_keys

Revision ID: c1437ab4f194
Revises: 6ec551602b22
Create Date: 2026-04-06 22:21:47.509351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1437ab4f194'
down_revision: Union[str, Sequence[str], None] = '6ec551602b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_llm_keys', sa.Column('allowed_models', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_llm_keys', 'allowed_models')
    # ### end Alembic commands ###
