"""add max_collaboration_depth to organizations

Revision ID: dcd8e2e3e6ad
Revises: 0873f1390f28
Create Date: 2026-04-08 11:10:41.155371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd8e2e3e6ad'
down_revision: Union[str, Sequence[str], None] = '0873f1390f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('max_collaboration_depth', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_collaboration_depth')
    # ### end Alembic commands ###
