"""add_invitations_table

Revision ID: e4f3e8e640ce
Revises: b3f7c1a29e04
Create Date: 2026-03-12 22:10:26.864991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f3e8e640ce'
down_revision: Union[str, Sequence[str], None] = 'b3f7c1a29e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_deleted_at'), 'invitations', ['deleted_at'], unique=False)
    op.create_index('uq_invitation_pending', 'invitations', ['org_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_invitation_pending', table_name='invitations', postgresql_where=sa.text("status = 'pending' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_invitations_deleted_at'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
