"""add org leave requests

Revision ID: ec27348942b6
Revises: f40cdac940d6
Create Date: 2026-06-05 16:41:37.988495

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec27348942b6'
down_revision: str | Sequence[str] | None = 'f40cdac940d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_leave_requests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_leave_requests_deleted_at'), 'org_leave_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_org_leave_requests_org_id'), 'org_leave_requests', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_leave_requests_status'), 'org_leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_org_leave_requests_user_id'), 'org_leave_requests', ['user_id'], unique=False)
    op.create_index('uq_org_leave_request_pending', 'org_leave_requests', ['user_id', 'org_id'], unique=True, postgresql_where=sa.text("status = 'pending' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_org_leave_request_pending', table_name='org_leave_requests', postgresql_where=sa.text("status = 'pending' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_org_leave_requests_user_id'), table_name='org_leave_requests')
    op.drop_index(op.f('ix_org_leave_requests_status'), table_name='org_leave_requests')
    op.drop_index(op.f('ix_org_leave_requests_org_id'), table_name='org_leave_requests')
    op.drop_index(op.f('ix_org_leave_requests_deleted_at'), table_name='org_leave_requests')
    op.drop_table('org_leave_requests')
    # ### end Alembic commands ###
