"""add engine_versions table

Revision ID: effcea6592fc
Revises: 0fd3d44ae8b3
Create Date: 2026-04-04 07:59:33.998948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effcea6592fc'
down_revision: Union[str, Sequence[str], None] = '0fd3d44ae8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_versions',
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('image_tag', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_versions_deleted_at'), 'engine_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_engine_versions_runtime'), 'engine_versions', ['runtime'], unique=False)
    op.create_index('uq_engine_version_runtime_version', 'engine_versions', ['runtime', 'version'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_engine_version_runtime_version', table_name='engine_versions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_engine_versions_runtime'), table_name='engine_versions')
    op.drop_index(op.f('ix_engine_versions_deleted_at'), table_name='engine_versions')
    op.drop_table('engine_versions')
    # ### end Alembic commands ###
